kind: ethereum/contract
name: MolochV22Template
network:
source:
  abi: V22Moloch
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/v2-mapping.ts
  entities:
    - Shaman
  abis:
    - name: V22Moloch
      file: ./abis/V22Moloch.json
  eventHandlers:
    - event: "SetShaman(indexed address,bool)"
      handler: handleSetShaman
