kind: ethereum/contract
name: V22AndSafeMinionFactoryv3
network:
source:
  address: ""
  abi: V22AndSafeMinionFactory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Shaman
    - MinionSafeConfig
  abis:
    - name: V22AndSafeMinionFactory
      file: ./abis/V22AndSafeMinionFactory.json
  eventHandlers:
    - event: SummonComplete(address,indexed address,address,address,string)
      handler: handleSummonComplete
  file: ./src/v22-safe-minion-factory-mapping.ts
