kind: ethereum/contract
name: YeeterERC20Factory
network:
source:
  address: ""
  abi: YeeterERC20Factory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Shaman
    - Token
    - YeeterConfig
  abis:
    - name: YeeterERC20Factory
      file: ./abis/YeeterERC20Factory.json
    - name: ERC20
      file: ./abis/ERC20.json
  eventHandlers:
    - event: SummonYeetComplete(indexed address,address,address,uint256,uint256,uint256,uint256,uint256,string,bool)
      handler: handleSummonYeeter
    - event: "PlatformFeeUpdate(uint256,uint256)"
      handler: handlePlatformFeeUpdate
  file: ./src/yeeter-erc20-factory-mapping.ts
